apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dev-hello-destination
spec:
  host: dev-hello-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2